#!/bin/bash

export DISPLAY=:0
export XAUTHORITY=/var/run/lightdm/james/xauthority
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin
/usr/bin/feh --bg-fill --randomize /home/james/Pictures/*.jpg

